#data
dataset: nuscenes
path: #path to nuscenes
version: v1.0-trainval
category_name: Car
sample_rate: 0.2
seed: 1
search_bb_scale: 1.25
search_bb_offset: 2
model_bb_scale: 1.25
model_bb_offset: 0
sample_num: 3
forward_bb_scale: 0
forward_bb_offset: 10
template_size: 512
search_size: 1024
random_sample: False
sample_per_epoch: -1
degrees: True # use degrees or radians
box_aware: True
num_candidates: 4
up_axis: [ 0,0,1 ]
preload_offset: 0
key_frame_only: True
train_split: train_track
val_split: val
test_split: val
min_points: 1
train_type: train_siamese
cycle: True
mix_up_search: True
mix_up_template: False
transformation: True
data_limit_box: False

#model configuration
net_model: CYCLEBAT
use_fps: True
normalize_xyz: False
feature_channel: 256 #the output channel of backbone
hidden_channel: 256 #the hidden channel of xcorr
out_channel: 256 #the output channel of xcorr
vote_channel: 256 #the channel for vote aggregation
num_proposal: 64
k: 4
use_search_bc: False
use_search_feature: False
bc_channel: 9

#loss configuration
objectiveness_weight: 1.5
box_weight: 0.2
vote_weight: 1.0
seg_weight: 0.2
bc_weight: 1.0


objectiveness_weight_backward: 3.0
box_weight_backward: 0.4
vote_weight_backward: 2.0
seg_weight_backward: 0.4
bc_weight_backward: 2.0


# testing config
reference_BB: previous_result
shape_aggregation: firstandprevious
use_z: False
limit_box: True
IoU_space: 3

#training
batch_size: 50 #batch_size per gpu
workers: 4
epoch: 200
from_epoch: 0
lr: 0.01

optimizer: SGD
lr_decay_step: 1
lr_decay_rate: 1
wd: 0.00005
gradient_clip_val: 0.0
