#data
dataset: kitti
path: #path to KITTI training
category_name: Van # [Car, Van, Pedestrian, Cyclist, All]
sample_rate: 0.1
seed: 1
search_bb_scale: 1.25
search_bb_offset: 2
model_bb_scale: 1.25
model_bb_offset: 0
template_size: 512
search_size: 1024
random_sample: False
sample_per_epoch: -1
degrees: True # use degrees or radians
num_candidates: 4
coordinate_mode: camera
up_axis: [0,-1,0]
train_split: train
val_split: test
test_split: test
preload_offset: 10
train_type: train_siamese
cycle: False
mix_up_search: False
mix_up_template: False
transformation: False
data_limit_box: True

#model configuration
net_model: P2B
use_fps: False
normalize_xyz: False
feature_channel: 256 #the output channel of backbone
hidden_channel: 256 #the hidden channel of xcorr
out_channel: 256 #the output channel of xcorr
vote_channel: 256 #the channel for vote aggregation
num_proposal: 64

#loss configuration
objectiveness_weight: 1.5
box_weight: 0.2
vote_weight: 1.0
seg_weight: 0.2

# testing config
reference_BB: previous_result
shape_aggregation: firstandprevious
use_z: False
limit_box: True
IoU_space: 3

#training
batch_size: 48
workers: 4
epoch: 60
from_epoch: 0
lr: 0.001
optimizer: Adam
lr_decay_step: 12
lr_decay_rate: 0.2
wd: 0
gradient_clip_val: 0.0
